### ISSUE TITLE
chainer not compatible with cudnn-7.0-linux-x64-v4.0

### ISSUE THREAD

**Issue by nushio3** [pfnet/chainer#835]
Running `python setup.py build` in master branch of e99cf1594c5bc70825bd156f6684a37ef6ffe0c5 results in following error, when `cudnn-7.0-linux-x64-v4.0` is in path.

The same commit successfully builds with `cudnn-6.5-linux-x64-v2` .

````
cupy/cuda/cudnn.cpp:4926:398: error: cannot convert ‘void*’ to ‘cudnnConvolutionBwdFilterAlgo_t’ for argument ‘8’ to ‘cudnnStatus_t cudnnConvolutionBackwardFilter(cudnnHandle_t, const void*, cudnnTensorDescriptor_t, const void*, cudnnTensorDescriptor_t, const void*, cudnnConvolutionDescriptor_t, cudnnConvolutionBwdFilterAlgo_t, void*, size_t, const void*, cudnnFilterDescriptor_t, void*)’

   __pyx_v_status = cudnnConvolutionBackwardFilter(((cudnnHandle_t)__pyx_v_handle), ((void *)__pyx_v_alpha), ((cudnnTensorDescriptor_t)__pyx_v_srcDesc), ((void *)__pyx_v_srcData), ((cudnnTensorDescriptor_t)__pyx_v_diffDesc), ((void *)__pyx_v_diffData), ((cudnnConvolutionDescriptor_t)__pyx_v_convDesc), ((void *)__pyx_v_beta), ((cudnnFilterDescriptor_t)__pyx_v_gradDesc), ((void *)__pyx_v_gradData));

                                                                                                                                                                                                                                                                                                                                                                                                              ^

cupy/cuda/cudnn.cpp: In function ‘PyObject* __pyx_f_4cupy_4cuda_5cudnn_convolutionBackwardData(size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t, size_t, int)’:

cupy/cuda/cudnn.cpp:5145:402: error: cannot convert ‘void*’ to ‘cudnnConvolutionBwdDataAlgo_t’ for argument ‘8’ to ‘cudnnStatus_t cudnnConvolutionBackwardData(cudnnHandle_t, const void*, cudnnFilterDescriptor_t, const void*, cudnnTensorDescriptor_t, const void*, cudnnConvolutionDescriptor_t, cudnnConvolutionBwdDataAlgo_t, void*, size_t, const void*, cudnnTensorDescriptor_t, void*)’

   __pyx_v_status = cudnnConvolutionBackwardData(((cudnnHandle_t)__pyx_v_handle), ((void *)__pyx_v_alpha), ((cudnnFilterDescriptor_t)__pyx_v_filterDesc), ((void *)__pyx_v_filterData), ((cudnnTensorDescriptor_t)__pyx_v_diffDesc), ((void *)__pyx_v_diffData), ((cudnnConvolutionDescriptor_t)__pyx_v_convDesc), ((void *)__pyx_v_beta), ((cudnnTensorDescriptor_t)__pyx_v_gradDesc), ((void *)__pyx_v_gradData));

                                                                                                                                                                                                                                                                                                                                                                                                                  ^

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_ubuntu/chainer/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-KqXMta-record/install-record.txt --single-version-externally-managed --compile --user failed with error code 1 in /tmp/pip_build_ubuntu/chainer
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 235, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 42: ordinal not in range(128)
````

**Comment by unnonouno** [comment]
Chainer does not support cuDNN v4 now. It is because ABI is broken.
We are now working at #756.

**Comment by nushio3** [comment]
Thank you for your information! I didn't notice of #756 (I had searched for cudnn 7.0, should have searched for v4....) I guess it would be good for us to close this ticket and wait for #756 to be merged.

**Comment by unnonouno** [comment]
Now cudnn v4-rc works correctly. Please check it.

**Comment by nushio3** [comment]
Thank you! I'll give it a try.
