### ISSUE TITLE
build fail on cudnn 7.0-v4.0

### ISSUE THREAD

**Issue by knok** [pfnet/chainer#1727]
I use CUDA 7.0.28 with cuDNN 4.0.
According to the install document, v1.16.0 supports this version.
http://docs.chainer.org/en/stable/install.html

But I tried to install, I can't compile cupy/cuda/cudnn.cpp with gcc and clang.
clang said:
```
% clang -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fpermissive -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/cuda/include -I/usr/include/python3.4m -I/opt/3gpu/include/python3.4m -c cupy/cuda/cudnn.cpp
cupy/cuda/cudnn.cpp:9081:20: error: no matching function for call to
      'cudnnBatchNormalizationBackward'
  __pyx_v_status = cudnnBatchNormalizationBackward(((cudnnHandle_t)__pyx...
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/cuda/include/cudnn.h:1211:27: note: candidate function not viable:
      requires 17 arguments, but 19 were provided
cudnnStatus_t CUDNNWINAPI cudnnBatchNormalizationBackward(
                          ^
1 error generated.
```
It seems a mismatch numbers of arguments on cudnnBatchNormalizationBackward.

Is chainer still supports cudnn v4?
At least, chainer v1.9.1 works fine on my environment.

**Comment by gwtnb** [comment]
> Is chainer still supports cudnn v4?

Yes.

Could you write your environment (OS, versions of compilers, version of installed Cython, etc.) more specifically?

Additionally, could you run `git bisect`?

```sh
# in some working directory
git clone https://github.com/pfnet/chainer.git
cd chainer

# uninstall chainer
pip uninstall -y chainer  # note that you may have to run this command more than once

git bisect start v1.16.0 v1.9.1

git bisect run python setup.py clean develop
```

**Comment by knok** [comment]
My environment is the following:
Debian Jessie(8.5) 
Linux 3.16.7
gcc 4.9.2 (Debian package)
Python 3.4.2 (Debian package)

git bisect points the following commit:
```
commit e22d850784bbf9a6cad0b200c7a5104e4cdc1745
Author: Yuya Unno <unnonouno@gmail.com>
Date:   Thu May 19 19:29:58 2016 +0900

    Implement transpose sequence function

```

**Comment by knok** [comment]
git bisect points the following comit:

```
commit 10e3d1db53dc6128ff5be1bb3fd1505de4decb3f
Author: Brian Vogel <vogel@preferred.jp>
Date:   Sun Jul 31 15:48:03 2016 +0900

    Added typedef for cudnnBatchNormMode_t for case when cuDNN version less than  v5.
```

**Comment by knok** [comment]
git bisect points the following commit:

```
10e3d1db53dc6128ff5be1bb3fd1505de4decb3f is the first bad commit
commit 10e3d1db53dc6128ff5be1bb3fd1505de4decb3f
Author: Brian Vogel <vogel@preferred.jp>
Date:   Sun Jul 31 15:48:03 2016 +0900

    Added typedef for cudnnBatchNormMode_t for case when cuDNN version less than v5.
```

**Comment by gwtnb** [comment]
Thank you, we will investigate this issue.

**Comment by gwtnb** [comment]
I could not reproduce the compilation error in a similar environment using Docker.

**Comment by knok** [comment]
I tried to build this commit on my environment, however building was succeed.
I'll try to run git bisect by hand.

**Comment by knok** [comment]
git bisect by hand points the same commit.
The error message is:
```
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/cuda/include -I/usr/include/python3.4m -I/opt/3gpu/include/python3.4m -c cupy/cuda/cudnn.cpp -o build/temp.linux-x86_64-3.4/cupy/cuda/cudnn.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from cupy/cuda/cudnn.cpp:272:0:
cupy/cuda/cupy_cudnn.h:120:13: error: conflicting declaration ‘typedef int cudnnnatchNormMode_t’
 typedef int cudnnBatchNormMode_t;
             ^
In file included from cupy/cuda/cupy_cudnn.h:9:0,
                 from cupy/cuda/cudnn.cpp:272:
/usr/local/cuda/include/cudnn.h:1121:3: note: previous declaration as ‘typedef eeum cudnnBatchNormMode_t cudnnBatchNormMode_t’
 } cudnnBatchNormMode_t;
   ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```
According to cupy/cuda/cupy_cudnn.h:
```
#if CUDNN_VERSION < 5000

// ***_v3 functions are not declared in cuDNN v2, v3 and v4.
// Following definitions are for compatibility with cuDNN v5.

#define cudnnActivationForward_v3 cudnnActivationForward
#define cudnnActivationBackward_v3 cudnnActivationBackward
#define cudnnSetFilter4dDescriptor_v3 cudnnSetFilter4dDescriptor
#define cudnnSetFilterNdDescriptor_v3 cudnnSetFilterNdDescriptor
#define cudnnSetPooling2dDescriptor_v3 cudnnSetPooling2dDescriptor
#define cudnnSetPoolingNdDescriptor_v3 cudnnSetPoolingNdDescriptor
typedef int cudnnBatchNormMode_t;
```
However, cudnnBatchNormMode_t is defined by cuDNN(cudnn.h):
```
#define CUDNN_MAJOR      4
#define CUDNN_MINOR      0
#define CUDNN_PATCHLEVEL 4

#define CUDNN_VERSION    (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + UDNN_PATCHLEVEL)

(snip)
typedef enum
{
    // bnScale, bnBias tensor dims are 1xCxHxWx.. (one value per CHW...-slice, normalized over N slice)
    CUDNN_BATCHNORM_PER_ACTIVATION = 0,

    //bnScale, bnBias tensor dims are 1xCx1x1 (one value per C-dim normalized over Nx1xHxW subtensors)
    CUDNN_BATCHNORM_SPATIAL        = 1,
} cudnnBatchNormMode_t;
```

My baremetal machine environment is:
cuDNN 4.0.4
CUDA 7.0
Debian 8.4 (a little bit old)
Linux 3.16.7
gcc 4.9.2 (Debian package)
Python 3.4.2 (Debian package)
Cython (0.24)

**Comment by knok** [comment]
I'll try to make similar docker environment and test it.

**Comment by knok** [comment]
Maybe I can understand the reason.
I installed cudnn-7.0-linux-x64-v4.0-rc.tgz, it could be non-official release version.
Sorry my wrong report.
