### ISSUE TITLE
Compilation error with CUDA 7.0 on Jetson TK1

### ISSUE THREAD

**Issue by robertostling** [pfnet/chainer#2083]
I am unable to compile Chainer/CuPy on my Jetson TK1 system (based on Ubuntu 16.04, same error on the previous 14.04 version), either via the pip distribution or directly from the github repo. CUDA 7.0 is installed. I get the following error message:

```
In file included from cupy/cuda/cublas.cpp:480:0:
cupy/cuda/cupy_cuda.h: In function ‘cublasStatus_t cublasSgemmEx(...)’:
cupy/cuda/cupy_cuda.h:43:33: error: conflicting declaration of C function ‘cublasStatus_t cublasSgemmEx(...)’
 cublasStatus_t cublasSgemmEx(...) {
                                 ^
In file included from /usr/local/cuda/include/cublas_v2.h:65:0,
                 from cupy/cuda/cupy_cuda.h:23,
                 from cupy/cuda/cublas.cpp:480:
/usr/local/cuda/include/cublas_api.h:1587:39: note: previous declaration ‘cublasStatus_t cublasSgemmEx(cublasHandle_t, cublasOperation_t, cublasOperation_t, int, int, int, const float*, const void*, cublasDataType_t, int, const void*, cublasDataType_t, int, const float*, void*, cublasDataType_t, int)’
 CUBLASAPI cublasStatus_t CUBLASWINAPI cublasSgemmEx  (cublasHandle_t handle, 
                                       ^
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
```

Does anyone know what's going wrong here?

**Comment by robertostling** [comment]
Everything works with CUDA 6.5, so closing this issue.
